services:
  content-agency:
    ports:
      - "4000:4000"
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/dev/content-agency/Dockerfile
    container_name: app-content-agency

